jobs:
  Backend:
    name: Backend
    steps:
      - type: gradle
        working-directory: alarm-management
        name: Build
        tasks: build
        use-gradle-wrapper: 'true'
    enable-dependency-cache: true
